Rails.application.config.assets.version = '1.0'

Rails.application.config.assets.paths << Rails.root.join('node_modules')

Rails.application.config.assets.precompile += %w( bootstrap.css )
Rails.application.config.assets.precompile += %w( style.css )
Rails.application.config.assets.precompile += %w( font-awesome.css )
Rails.application.config.assets.precompile += %w( SidebarNav.min.css )
Rails.application.config.assets.precompile += %w( custom.css )
Rails.application.config.assets.precompile += %w( owl.carousel.css )
Rails.application.config.assets.precompile += %w( monthly.css )
Rails.application.config.assets.precompile += %w( print.css )
Rails.application.config.assets.precompile += %w( invoice.css )

Rails.application.config.assets.precompile += %w( jquery-1.11.1.min.js )
Rails.application.config.assets.precompile += %w( modernizr.custom.js )
# Rails.application.config.assets.precompile += %w( Chart.js )
# Rails.application.config.assets.precompile += %w( amcharts.js )
Rails.application.config.assets.precompile += %w( custom.js )
Rails.application.config.assets.precompile += %w( main.js )
Rails.application.config.assets.precompile += %w( print.js )
Rails.application.config.assets.precompile += %w( invoice.js )
# Rails.application.config.assets.precompile += %w( pie-chart.js )
Rails.application.config.assets.precompile += %w( owl.carousel.js )
# Rails.application.config.assets.precompile += %w( Chart.bundle.js )
# Rails.application.config.assets.precompile += %w( utils.js )
Rails.application.config.assets.precompile += %w( classie.js )
# Rails.application.config.assets.precompile += %w( SimpleChart.js )
Rails.application.config.assets.precompile += %w( jquery.nicescroll.js )
Rails.application.config.assets.precompile += %w( scripts.js )
Rails.application.config.assets.precompile += %w( SidebarNav.min.js )
Rails.application.config.assets.precompile += %w( bootstrap.js )
Rails.application.config.assets.precompile += %w( monthly.js )
Rails.application.config.assets.precompile += %w( serial.js )
